workflows:
  debug-build:
    name: Debug APK Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      flutter: stable
    scripts:
      - name: Get dependencies
        script: |
          cd app
          flutter pub get
      - name: Build debug APK
        script: |
          cd app
          flutter build apk --debug
    artifacts:
      - app/build/app/outputs/flutter-apk/app-debug.apk
