workflows:
  debug-android:
    name: Debug Android APK
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      vars:
        GRADLE_OPTS: "-Xmx4096m"
    scripts:
      - name: Build debug APK
        script: ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/apk/debug/app-debug.apk
