workflows:
  sample-workflow:
    name: Codemagic Sample Workflow
    max_build_duration: 120
    instance_type: mac_mini_m2

    scripts:
      - name: Make gradlew executable
        script: chmod +x gradlew
      - name: Build debug APK
        script: ./gradlew assembleDebug
