workflows:
  android-apk:
    name: Android APK Build
    max_build_duration: 30
    environment:
      java: 17
    scripts:
      - name: Build APK
        script: ./gradlew assembleRelease
    artifacts:
      - app/build/outputs/apk/release/*.apk
