workflows:
  android-workflow:
    name: Android Debug Build
    environment:
      vars:
        JAVA_HOME: "/usr/lib/jvm/java-17-openjdk"
    scripts:
      - name: Assemble debug
        script: |
          ./gradlew assembleDebug
    publishing:
      artifacts:
        - app/build/outputs/**/*.apk
